[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmd = "npm install && npm run build"

[start]
cmd = "serve -s build -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
